config/routes.rb
IbabaiP::Application.routes.draw do
  
  get "users/new"
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :qas, only: [:index, :new, :create]
  
  root 'static_pages#product'
  match '/partners', to: 'static_pages#partners', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'
  match '/leads', to: 'static_pages#new', via: 'get'
  match '/leads', to: 'static_pages#create', as: "modal", via: 'post'

end

app/models/lead.rb
class Lead < ActiveRecord::Base
	attr_accessible :fname, :lname, :company, :tel, :email
	before_save { self_email = email.downcase }
	
	validates :fname, presence: true
	validates :lname, presence: true
	validates :company, presence: true
	validates :tel, presence: true
	validates :email, presence: true



end

app/models/qa.rb
class Qa < ActiveRecord::Base
	attr_accessible :question, :answer, :email
	default_scope -> { order('created_at DESC') }
	before_save { self.email = email.downcase }
	validates :question, presence: true, length: { maximum: 140 }
		
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  before_save { self_email = email.downcase }

  validates :email, presence: true
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html, :js

  def index
    @leads = Lead.all
  end

  def new
  	@lead = Lead.new
  end

  def create
  	@lead = Lead.new(params[:lead]) 
  	if @lead.save
      flash.now[:success] = "Thank you! We'll be back shortly..."
      respond_with @lead
    else
      flash.now[:error] = "All fields should be filled in!"
      
    end
  end

end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  
  def index 
    @qas = Qa.where.not(answer: nil)           
  end

  def create
    @qa = Qa.new(qa_params)
    if @qa.save
      flash[:success] = "Thanks for your question! We'll reply asap."
      redirect_to faq_url
    else
      flash[:error] = "Oops! No more than 140 chars. Try again!"
      redirect_to faq_url

    end
  end


  def destroy
  end

  private
    def qa_params
      params.require(:qa).permit(:question, :email)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   
  def product
  end

  def partners
  end

  def about
  end

  
  def contacts  	
  end

  def faq
    @qas = Qa.where.not(answer: nil) 
    @qa = Qa.new
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user=User.new
  end

  def create
  	if @user.save
  		redirect to user_path
  	else
  		render 'new'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "ibabai"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/qas_helper.rb
module QasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
		<div class="row" id="footer-bar">
			<button type="button" class= "btn btn-primary btn-lg" data-toggle="modal" data-target="#downModal" id="download">Dowhload App Now</button>
					<div class="modal fade" id="downModal" tabindex="-1" role="dialog" aria-labelledby="downModalLabel" aria-hidden="true">
  						<div class="modal-dialog">
    						<div class="modal-content">
      							<div class="modal-header">
        							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        							<h4 class="modal-title" id="downModalLabel">Download in two easy steps</h4>
      							</div>
      							<div class="modal-body">
        							The instructions to be plased here
      							</div>
      							<div class="modal-footer">
        							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        							<button type="button" class="btn btn-primary">Start Download</button>
      							</div>
    						</div><!-- /.modal-content -->
  						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
					
			     <%= render "layouts/modal" %>

	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
		<div class="navbar-inner">
			<div class="container">
				<%= image_tag "logo.png", id: "logo" %>
				<h3 class="navbar-text" id="page-name"><%= yield(:title) %></h3>
				<nav>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Product", root_path %></li>
						<li><%= link_to "Partners", partners_path %></li>
						<li><%= link_to "About", about_path %></li>
						<li><%= link_to "FAQ", faq_path %></li>
						<li><%= link_to "Contacts", contacts_path %></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_mform.html.erb
<div class="modal-body">

  <div class="row">
    <div class="col-md-6 col-md-offset-3" id="lead-form">
      <%= form_for(Lead.new, remote: true) do |f| %>

        <%= f.label :fname, "First name" %>
        <%= f.text_field :fname %>

        <%= f.label :lname, "Last name" %>
        <%= f.text_field :lname %>

        <%= f.label :company, "Company" %>
        <%= f.text_field :company %>

        <%= f.label :tel, "Telephone" %>
        <%= f.text_field :tel %>

        <%= f.label :email, "E-mail" %>
        <%= f.text_field :email %>

        <%= f.submit "Send", class: "btn btn-primary btn-sm" %>

                      
      <% end %>       
        
    </div>      
  </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      
</div>    
      

app/views/layouts/_modal.html.erb
<button type= "button" class= "btn btn-primary btn-lg"     data-toggle= "modal" data-target= "#clientModal" id= "lead">Become Partner</button>
      	
          <div class="modal fade" id="clientModal" tabindex="-1" role="dialog" aria-labelledby="clientModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title" id="clientModalLabel">Fill in the form and we'll call you back shortly...</h4>
                    </div>
                        <%= render "layouts/mform" %>
                    
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA46T72I0fbZGFgRTPlIQpRZThAAOPXn1s&sensor=false">
  </script>
  <script type="text/javascript">
  function initialize()
	{
	var mapOptions = {
  		center:new google.maps.LatLng(50.479357, 30.521178),
  		zoom: 8,
      mapTypeId: google.maps.MapTypeId.ROADMAP
  		};
	var map=new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
	}

	google.maps.event.addDomListener(window, 'load', initialize);
</script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
  <div class = "row" id="main">
	
		<%= yield %>

	</div>
	<%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/leads/_mform.html.erb
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#clientModal" id="client-lead">Become Partner</button>
      	
          <div class="modal fade" id="clientModal" tabindex="-1" role="dialog" aria-labelledby="clientModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title" id="clientModalLabel">Fill in the form and we'll call you back shortly...</h4>
                    </div>
                    <div class="modal-body">
                      The form to be placed here
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <button type="button" class="btn btn-primary">Send</button>
                    </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->

app/views/qas/_qa.html.erb
<li>
	<sppan><strong>Q:</strong></span>
	<span class="quest"><%= qa.question %></span><br>
	<span><strong>A:</strong></span>
	<span class="ans"><%= qa.answer %></span><br>
	<span class="timestamp">
		Posted <%= time_ago_in_words(qa.created_at) %> ago.
	</span>
</li>

			
		
	
	

app/views/shared/_error_messages.html.erb
<% if @qa.errors.any? %>
	<div id="error_expl">
		<div class="alert alert-danger">
			You have <%= pluralize(@qa.errors.count, "fuck-up") %>
		</div>
		<ul>
			<% @qa.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_qa_form.html.erb
  <%= form_for( @qa ) do |f| %>
  <div class="countdown"></div> 
  <div class="row">          
    <div class= "col-md-8" id="field">
      <%= f.text_area :question, placeholder: "Can't find answer? Ask your question here..." %>
     </div>
    <div class="col-md-4" id="sbt">
      <%= f.label :email, "Want reply with e-mail?" %>
      <%= f.text_field :email %>    
    
      <%= f.submit "Post", class: "btn btn-lg" %>
          
    </div>
</div>
  <% end %>

app/views/static_pages/FAQ.html.erb
<% provide(:title, "Frequently Asked Questions") %>
<div class = "row", id="contacts">
	<div class="col-md-6">
		<div class="panel-group" id="accordion">
  			<div class="panel panel-default">
    			<div class="panel-heading">
      				<h4 class="panel-title">
        				<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          					FAQ #1
        				</a>
      				</h4>
    			</div>
    			<div id="collapseOne" class="panel-collapse collapse in">
      				<div class="panel-body">
        				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      				</div>
    			</div>
  			</div>
  			<div class="panel panel-default">
    			<div class="panel-heading">
      				<h4 class="panel-title">
        				<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          					FAQ #2
        				</a>
      				</h4>
    			</div>
    			<div id="collapseTwo" class="panel-collapse collapse">
      				<div class="panel-body">
        				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      				</div>
    			</div>
  			</div>
  			<div class="panel panel-default">
    			<div class="panel-heading">
      				<h4 class="panel-title">
        				<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          					FAQ #3
        				</a>
      				</h4>
    			</div>
    			<div id="collapseThree" class="panel-collapse collapse">
      				<div class="panel-body">
        				Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      				</div>
    			</div>
  			</div>
		</div>
   		
	</div>

	<div class="col-md-6">    
		<div id = "feed">
      <h4><strong>The latest Q&A.</strong></h4>
      <% if @qas.any? %>
        <ol class="qa">    
          <%= render @qas %>
        </ol>
      <% end %>                      
    </div>
    <div class="qform">

      <%= render "shared/qa_form" %>
      
     </div>
     <div id="flash">
        <% flash.each do |key, value| %>
          <div class= "alert alert-<%= key %>"><%= value %></div>
        <% end %>
      </div>
     <div id="hot-line">
        <span>Customer Support 24/7</span><br>
        <span><strong>+380 800 700 60 50</strong></span>
     </div>		
	</div>
</div>

app/views/static_pages/_flash.html.erb
<div class= "row" id= "message">

	<% flash.each do |key, value| %>
		<div class= "alert alert-<%= key %>"><%= value %></div>
	<% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About. Get to know us.') %>
<div class = "row", id="contacts">
	<div class="col-md-4">

   		<%= image_tag "cp/a1.jpg", id: "a1" %>
	</div>

	<div class="col-md-8">
		Some stuff about us.
		
	</div>
</div>

	

app/views/static_pages/contacts.html.erb
<% provide(:title, "Contacts. You are always welcome.") %>
<div class = "row", id="contacts">
	<div class="col-md-6">

   		<div class="google-map-canvas" id="map-canvas"></div>
	</div>

	<div class="col-md-6">
		<address>
			<strong>IBABAI, INC.</strong><br>
			795 Folsom Ave, Suite 600<br>
			San Francisco, CA 94107<br>
			<abbr title="Phone">P:</abbr> (123) 456-7890<br>
			<a href="mailto:#">first.last@ibabai.com</a>
		</address>
		
	</div>
</div>


		

	

app/views/static_pages/create.js.erb
	$('#new_lead').on("ajax:success", function(event, data, status, xhr) {

		$('#message').remove();

	
		$('#lead-form').append("<%= escape_javascript(render('static_pages/flash')) %>");

		<% if flash[:success] %>

			$(this).each(function(){ this.reset() });
				$(".alert-error").remove();
					window.setTimeout(function() {$('#clientModal').modal("hide");}, 3000)  

	
		<% end %>
	

	});




	 				

app/views/static_pages/partners.html.erb
<% provide(:title, "Partners. We care about your customers") %>

<div id="carousel-c" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-c" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-c" data-slide-to="1"></li>
    <li data-target="#carousel-c" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "cp/cc1.jpg", id: "pr" %>      
    </div>

    <div class="item">
    	<%= image_tag "cp/cc2.jpg", id: "pr" %>
    </div>
    <div class="item">
    	<%= image_tag "cp/cc3.jpg", id: "pr" %>
    </div>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-c" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-c" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

	

app/views/static_pages/product.html.erb
<% provide(:title, "Product. How this works.") %>
<div id="carousel-p" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-p" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-p" data-slide-to="1"></li>
    <li data-target="#carousel-p" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "cp/cp1.jpg", id: "pr" %>      
    </div>

    <div class="item">
    	<%= image_tag "cp/cp2.jpg", id: "pr" %>
    </div>
    <div class="item">
    	<%= image_tag "cp/cp3.jpg", id: "pr" %>
    </div>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-p" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-p" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
	
	

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>